server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5433/okkazo_auth_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  Kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

Kafka:
    topic:
        name: ${KAFKA_TOPIC_NAME:auth_events}

jwt:
  secret: ${JWT_SECRET:your-default-secret-key-change-this-in-production}
  access-token:
      expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:2592000000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}